const FETCH_REQUEST = 'FETCH_REQUEST';
const FETCH_SUCCESS = 'FETCH_SUCCESS';
const FETCH_FAILURE = 'FETCH_FAILURE';
const CHANGE_AREA = 'CHANGE_AREA';
const SELECT_MEAL = 'SELECT_MEAL';
const FETCH_MEAL_REQUEST = 'FETCH_MEAL_REQUEST';
const FETCH_MEAL_SUCCESS = 'FETCH_MEAL_SUCCESS';
const FETCH_MEAL_FAILURE = 'FETCH_MEAL_FAILURE';
const base_url = 'https://www.themealdb.com/api/json/v1/1/';

export {
  FETCH_REQUEST,
  FETCH_SUCCESS,
  FETCH_FAILURE,
  CHANGE_AREA,
  SELECT_MEAL,
  FETCH_MEAL_REQUEST,
  FETCH_MEAL_SUCCESS,
  FETCH_MEAL_FAILURE,
  base_url,
};
