const FETCH_REQUEST = 'FETCH_REQUEST';
const FETCH_SUCCESS = 'FETCH_SUCCESS';
const FETCH_FAILURE = 'FETCH_FAILURE';
const CHANGE_AREA = 'CHANGE_AREA';

export { FETCH_REQUEST, FETCH_SUCCESS, FETCH_FAILURE, CHANGE_AREA };
